apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: ap-southeast-2
  version: "1.25"

vpc:
  cidr: 192.168.0.0/16
  nat:
    gateway: HighlyAvailable

nodeGroups:
  - name: eks-node-group-spot-instances
    desiredCapacity: 3
    privateNetworking: true
    instancesDistribution:
      instanceTypes: ["t3.medium", "t3a.medium"]
      onDemandPercentageAboveBaseCapacity: 0
    labels: { lifecycle: Ec2Spot }

availabilityZones: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"] # This is required since in ap-southeast-2 only 2 subnets are created by default (https://eksctl.io/usage/vpc-networking/)